# Preliminaries
## Data manipulation

### Vectors
Single dimensional, singular axis arrays of numbers are usually called vectors

### Matrices
Two dimensional arrays are refferred to as matrices

### Tensors
Dimensions greater than 2 are usually referred to as k-th order tensors.

In [2]:
import torch

x = torch.arange(12, dtype=torch.float32)
print(x)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])


In [3]:
# The number of elements can be found like this:

x.numel()

12

In [4]:
# The shape of the tensor means the length along each axis, we can get it like this:

x.shape

torch.Size([12])

In [5]:
# We can transform our single dimension 12 value array to a 2 dimensional matrix of shape 3x4 like this:

transformed_matrix = x.reshape(3, 4)
print(transformed_matrix)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


In [16]:
transformed_matrix[0,3] # gets first row and 4th column
transformed_matrix[1,3] # gets second row and 4th column
transformed_matrix[2,3] # gets third row and 4th column
transformed_matrix[0, :] # gets first row
transformed_matrix[:, 0] # gets first column

tensor([0., 4., 8.])

In [17]:
# inferred transformation
inferred_matrix = x.reshape(3, -1)
print(inferred_matrix)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


In [7]:
# here's how we access the zeroth row and zeroth column of the matrix:
transformed_matrix[0,0].item()

0.0

In [8]:
# We can also access the entire row or column like this:
transformed_matrix[0,:]

tensor([0., 1., 2., 3.])

In [9]:
# or like this:
transformed_matrix[:,0]

tensor([0., 4., 8.])

In [10]:
# We can also access a range of values like this:
transformed_matrix[0, 1:3]

tensor([1., 2.])

In [11]:
# we can access any (n) column like this:
column = 1
transformed_matrix[:, column-1:column]

tensor([[0.],
        [4.],
        [8.]])

In [12]:
# We can also transpose the matrix like this:
transformed_matrix.t()

tensor([[ 0.,  4.,  8.],
        [ 1.,  5.,  9.],
        [ 2.,  6., 10.],
        [ 3.,  7., 11.]])

## Indexing and Slicing

In [ ]:
# gives the last row
transformed_matrix[-1]

tensor([ 8.,  9., 10., 11.])

In [ ]:
# first two rows
transformed_matrix[0:2]

tensor([[0., 1., 2., 3.],
        [4., 5., 6., 7.]])

In [ ]:
# first two rows and first two columns
transformed_matrix[0:2, :-2]

tensor([[0., 1.],
        [4., 5.]])

## Operations

In [38]:
t_n1 = torch.tensor([1, 2, 3])
t_n2 = torch.tensor([4, 5, 6])
t_sum = t_n1 + t_n2
print(t_sum)

tensor([5, 7, 9])


In [ ]:
# scalars
2 * t_n1

tensor([2, 4, 6])

## Broadcasting

In [44]:
t_n3 = torch.arange(3).reshape(3,-1) # reshaped to 3 rows and 1 column (3x1)
t_n4 = torch.arange(2).reshape(-1,2) # reshaped to 1 row and 2 columns (1x2)
t_n3, t_n4

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [45]:
# Broadcasting step
t_n3 + t_n4

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [ ]:
# Manually replicating the broadcast step
tensor1 = torch.tensor([[0,0], [1,1], [2,2]]) # expanded to 3x2
tensor2 = torch.tensor([[0,1], [0,1], [0,1]]) # expanded to 3x2
tensor1 + tensor2

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [ ]:
temp_tensor = torch.arange(12).reshape(-1,1)
expanded_tensor = temp_tensor.expand(-1, 4) # making 4 copies of the tensor column-wise
print(expanded_tensor)

tensor([[ 0,  0,  0,  0],
        [ 1,  1,  1,  1],
        [ 2,  2,  2,  2],
        [ 3,  3,  3,  3],
        [ 4,  4,  4,  4],
        [ 5,  5,  5,  5],
        [ 6,  6,  6,  6],
        [ 7,  7,  7,  7],
        [ 8,  8,  8,  8],
        [ 9,  9,  9,  9],
        [10, 10, 10, 10],
        [11, 11, 11, 11]])


In [74]:
temp_tensor_2 = torch.arange(4).reshape(1,-1)
expanded_tensor_2 = temp_tensor_2.expand(4, -1) # making 4 copies of the tensor row-wise
print(expanded_tensor_2)

tensor([[0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3]])


In [ ]:
# Tensor conditionals

xt1 = torch.tensor([1, 2, 3, 4])
xt2 = torch.tensor([4, 3, 2, 1])

xt1 == xt2 # all false, because no element is equal

tensor([False, False, False, False])

In [ ]:
xt1 < xt2 # first two are true, last two are false

tensor([ True,  True, False, False])

In [82]:
xt1.flip(dims=[0]) == xt2 # all true, because the order is reversed

tensor([True, True, True, True])