# Preliminaries
## Data manipulation

### Vectors
Single dimensional, singular axis arrays of numbers are usually called vectors

### Matrices
Two dimensional arrays are refferred to as matrices

### Tensors
Dimensions greater than 2 are usually referred to as k-th order tensors.

In [18]:
import torch

x = torch.arange(12, dtype=torch.float32)
print(x)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])


In [19]:
# The number of elements can be found like this:

x.numel()

12

In [20]:
# The shape of the tensor means the length along each axis, we can get it like this:

x.shape

torch.Size([12])

In [24]:
# We can transform our single dimension 12 value array to a 2 dimensional matrix of shape 3x4 like this:

transformed_matrix = x.reshape(3, 4)
print(transformed_matrix)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


In [36]:
# here's how we access the zeroth row and zeroth column of the matrix:
transformed_matrix[0,0].item()

0.0

In [37]:
# We can also access the entire row or column like this:
transformed_matrix[0,:]

tensor([0., 1., 2., 3.])

In [38]:
# or like this:
transformed_matrix[:,0]

tensor([0., 4., 8.])

In [39]:
# We can also access a range of values like this:
transformed_matrix[0, 1:3]

tensor([1., 2.])

In [50]:
# we can access any (n) column like this:
column = 1
transformed_matrix[:, column-1:column]

tensor([[0.],
        [4.],
        [8.]])

In [40]:
# We can also transpose the matrix like this:
transformed_matrix.t()

tensor([[ 0.,  4.,  8.],
        [ 1.,  5.,  9.],
        [ 2.,  6., 10.],
        [ 3.,  7., 11.]])