# Matrix Manipulations With Numpy

In [5]:
import numpy as np

m1 = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

In [29]:
print(f'Dimensions: {m1.ndim}')
print(f'Shape: {m1.shape}')
print(f'Num elements: {m1.size}')

Dimensions: 2
Shape: (3, 3)
Num elements: 9


In [38]:
m2 = np.array([[1,1,1],
               [1,1,1],
               [1,1,1]])

m1m2 = m1 * m2
print(m1m2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
